steps:
# Update container image on an existing VM instance
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'update-container'
  args: [
    'compute', 'instances', 'update-container', 'sharma-instance',
    '--zone=us-central1-a',
    '--container-image=asrma7/python-backend:latest',
    '--container-restart-policy=always'
  ]

# Timeout for the entire build process
timeout: '600s'

options:
  logging: CLOUD_LOGGING_ONLY
