steps:
# Deploy container to existing VM instance
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'deploy-container'
  args: [
    'compute', 'instances', 'create-with-container', 'sharma-instance',
    '--zone=us-central1-a',  # Specify your VM's zone
    '--container-image=asrma7/python-backend:latest',
    '--container-restart-policy=always'
  ]

# Timeout for the entire build process
timeout: '600s'

options:
  logging: CLOUD_LOGGING_ONLY
